replicaCount: 1
image:
  repository: artdtra
  tag: "v1.2.0-988165c"
  arch: "amd64"
  os: "linux"
secret:
  name: coding-session-1
  tokenKey: token
  tokenName: TELE_TOKEN
securityContext:
  privileged: true
